version: '3.8'

services:
  orchestrator:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - hw_predict_service
      - xgb_predict_service

  hw_predict_service:
    build: .
    ports:
      - "8002:8002"
    command: uvicorn src.api.hw_service:app --host 0.0.0.0 --port 8002

  xgb_predict_service:
    build: .
    ports:
      - "8001:8001"
    command: uvicorn src.api.xgb_service:app --host 0.0.0.0 --port 8001