# ===========================
# 1. XGBoost Service (The Heavy Model)
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgb-model
  template:
    metadata:
      labels:
        app: xgb-model
    spec:
      containers:
      - name: xgb-container
        image: energy-xgb:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /docs
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /docs
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: xgb-service
spec:
  selector:
    app: xgb-model
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

---
# ===========================
# 2. Holt-Winters Service (The Eco/Fallback Model)
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-model
  template:
    metadata:
      labels:
        app: hw-model
    spec:
      containers:
      - name: hw-container
        image: energy-hw:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: hw-service
spec:
  selector:
    app: hw-model
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

---
# ===========================
# 3. API Gateway (The Orchestrator)
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-container
        image: energy-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
          - name: XGB_SERVICE_URL
            value: "http://xgb-service:8001/predict/"
          - name: HW_SERVICE_URL
            value: "http://hw-service:8002/predict/"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# ===========================
# 4. GUI Deployment
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-gui
  template:
    metadata:
      labels:
        app: energy-gui
    spec:
      containers:
      - name: gui
        image: energy-gui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://api-service:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# GUI Service
apiVersion: v1
kind: Service
metadata:
  name: gui-service
spec:
  type: NodePort
  selector:
    app: energy-gui
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30001